project:
  type: book

book:
  title: "Exploratory analysis in R"
  author: "JC"
  chapters:
    - index.qmd
    - part: "Dataset overview"
      chapters:
        - look_for.qmd
        - Data dictionary.qmd
        - Frequency function for SPSS.qmd
        - Overview of SPSS data.qmd
    
format:
  html:
    theme: cosmo
    toc: true
    page-layout: full
    css: dense-notes.css
